version: '3'

services:
  web:
    build: .
    container_name: flask_app
    restart: on-failure
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=src/app.py
      - POSTGRES_HOST=postgres  # El nombre del servicio en lugar de localhost
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:14
    restart: on-failure
    container_name: ${DOCKER_CONTAINER}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_PORT}:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge